jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["14", "16"]
        name: Node ${{ matrix.node }} Tests
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  cache: "npm"
            - run: npm ci
            ## static: run type checks, formatting, linting
            - run: npm run check
            - run: npm run lint
            ## dynamic: run unit/feature/.. tests
            - run: npm run test
    coverage:
        needs: tests
        runs-on: ubuntu-latest
        name: Code Coverage Report
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
                with:
                    node-version: '16'
                    cache: "npm"
            - run: npm ci
            ## dynamic: run unit/feature/.. tests with coverage (multiple: html via lcov, cobertura, json, clover)
            - run: npm run coverage
            - name: Archive code coverage results
              uses: actions/upload-artifact@v2
                with:
                    name: code-coverage-report
                    path: |
                        coverage
                    retention-days: 7
    build:
        needs: tests
        runs-on: ubuntu-latest
        name: Build Distribution
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
                with:
                    node-version: '16'
                    cache: "npm"
            - run: npm ci
            ## build distribution in dist/
            - run: npm run build
            - name: Archive distribution
              uses: actions/upload-artifact@v2
                with:
                    name: dist
                    path: |
                        dist
                    retention-days: 7
