name: Tests & Testbuild

on:
    # Trigger the workflow on push or pull request,
    # but only for the main branch
    push:
        branches:
            - main
        paths-ignore:
            - "**.md"
    pull_request:
        branches:
            - main

jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node: ["14", "16"]
        name: Node ${{ matrix.node }} Tests
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node }}
                  cache: "npm"
            - run: npm ci
            ## static: run type checks, formatting, linting
            - run: npm run check
            - run: npm run lint
            ## dynamic: run unit/feature/.. tests
            - run: npm run test
    build:
        needs: tests
        runs-on: ubuntu-latest
        name: Build Distribution
        steps:
            - uses: actions/checkout@v2
            - name: Setup node
              uses: actions/setup-node@v2
              with:
                  node-version: "16"
                  cache: "npm"
            - run: npm ci
            ## build distribution in dist/
            - run: npm run build
